### ISSUE TITLE
404 - No se encuentra el deploy - error de dominio ?

### ISSUE THREAD

**Issue by n-zu** [FdelMazo/prode.click#1]
https://prode.click/ da error
![image](https://github.com/FdelMazo/prode.click/assets/66538092/8abd1268-5681-4479-ada1-fc3de6c10cfa)

pero sigue siendo accesible desde el deploy: https://prodeclick-oj31k2z2l-fdelmazo-team.vercel.app/

**Comment by FdelMazo** [comment]
Gracias @n-zu! Increiblemente... alguien (malvado) me hizo un denial of service hace unas horas. Me colapso la base de datos y empezó a andar todo mal. En medio del pánico, directamente tire abajo el dominio para poder arreglarlo, y ahora lo acabo de levantar de nuevo con un rate-limiter (flojo fix, pero no se mucho de trafico de red).

Hasta el proximo ataque!

**Comment by n-zu** [comment]
![this is why we cant have nice things](https://i.kym-cdn.com/photos/images/newsfeed/000/272/923/18b.jpg)

Gracias a vos! Buenisima app!

Que maldad atacar estas cosas  (╯°□°)╯︵ ┻━┻

Saludos !
